### ISSUE TITLE
Use Ec2 IAM profile

### ISSUE THREAD

**Issue by SonyDavid** [awslabs/aws-codedeploy-plugin#50]
It be nice to use the IAM profile of the Ec2 server that the plugin running on instead of providing keys.

**Comment by suryanarayanan** [comment]
Based on my understanding of your question if you are looking for a way to use the IAM profile of the ec2 jenkins server to kick off CodeDeploy deployment, you can already do that today.
In your CodeDeploy plugin configuration use the option "Use temporary credentials" instead of providing keys.  Upon selecting this option, by default the plugin uses instance profile to authenticate against CodeDeploy service.

**Comment by Jones2026** [comment]
This can be an issue though because it uses the master Jenkins instance instead of the slave on which the plugin is running. So it can assume the wrong role if you have your master Jenkins and slave Jenkins ec2 instances using different roles.

**Comment by SonyDavid** [comment]
Got it. Thank you.
